In [1]:
import pandas as pd
import numpy as np
from word2number import w2n
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("hiring.csv")

In [3]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
df.experience = df.experience.fillna("zero")

In [5]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
pip install word2number


[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
# a=0
# for i in df.experience:
#     df.experience[a] = w2n.word_to_num(i)
#     a+=1

df.experience = df.experience.apply(w2n.word_to_num)

In [8]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [9]:
import math
mean_test_score = math.floor(df["test_score(out of 10)"].mean())
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(mean_test_score)

In [10]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [11]:
linear_reg = linear_model.LinearRegression()
linear_reg.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df[["salary($)"]])

LinearRegression()

In [12]:
linear_reg.predict([[2,9,6]])

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [13]:
linear_reg.predict([[12,10,10]])

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])

In [14]:
linear_reg.intercept_

array([14992.65144669])

In [15]:
linear_reg.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [16]:
df["predicted salary"]=linear_reg.predict(df[["experience","test_score(out of 10)","interview_score(out of 10)"]])

In [17]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0                    8.0                           9      50000   
1           0                    8.0                           6      45000   
2           5                    6.0                           7      60000   
3           2                   10.0                          10      65000   
4           7                    9.0                           6      70000   
5           3                    7.0                          10      62000   
6          10                    7.0                           7      72000   
7          11                    7.0                           8      80000   

   predicted salary  
0      52090.467341  
1      45648.019642  
2      57964.229084  
3      64525.106136  
4      68325.211846  
5      60783.447853  
6      74796.883259  
7      79866.634840

In [23]:
import joblib

In [24]:
with open("multiplelinearreg_model", 'wb') as f:
    joblib.dump(linear_reg,f)

In [25]:
with open("multiplelinearreg_model", 'rb') as f:
    model = joblib.load(f)

In [26]:
model.predict([[12,10,10]])

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])